pipeline {
  agent any 
  options {
    timeout(time: 10, unit: 'MINUTES')
  }
  stages {
    stage('Review elements') {
      steps {
        sh "whoami"
        sh "podman run quay.io/podman/hello:latest"
      }
    }
    stage('Build basic_array') {
      steps {
        dir('basic_array') {
          sh """
            mkdir -p build
            cd build
            cmake ..
            make
            ./array
          """
        }
      }
    }
  }
}