pipeline {
  agent any 
  options {
    timeout(time: 10, unit: 'MINUTES')
  }
  stages {
    stage('Review elements') {
      steps {
        sh "whoami"
        sh "podman run quay.io/podman/hello:latest"
      }
    }
  }
}